version: '3'

services:
  confserv1:
    image: mongo:${MONGO_IMAGE_VERSION}
    command: mongod --configsvr --replSet ${CONFIG_SERVER1_CONTAINER_REPL_SET_NAME} --port ${CONFIG_SERVER1_CONTAINER_MONGO_PORT} --dbpath ${CONFIG_SERVER1_CONTAINER_DB_PATH}
    expose:
      - "${CONFIG_SERVER1_CONTAINER_MONGO_PORT}"
    networks:
      - mongo_net
    volumes:
      - confservvol1:${CONFIG_SERVER1_CONTAINER_DB_PATH}

  confserv2:
    image: mongo:${MONGO_IMAGE_VERSION}
    command: mongod --configsvr --replSet ${CONFIG_SERVER2_CONTAINER_REPL_SET_NAME} --port ${CONFIG_SERVER2_CONTAINER_MONGO_PORT} --dbpath ${CONFIG_SERVER2_CONTAINER_DB_PATH}
    expose:
      - "${CONFIG_SERVER2_CONTAINER_MONGO_PORT}"
    networks:
      - mongo_net
    volumes:
      - confservvol2:${CONFIG_SERVER2_CONTAINER_DB_PATH}

  confserv3:
    image: mongo:${MONGO_IMAGE_VERSION}
    command: mongod --configsvr --replSet ${CONFIG_SERVER3_CONTAINER_REPL_SET_NAME} --port ${CONFIG_SERVER3_CONTAINER_MONGO_PORT} --dbpath ${CONFIG_SERVER3_CONTAINER_DB_PATH}
    expose:
      - "${CONFIG_SERVER3_CONTAINER_MONGO_PORT}"
    networks:
      - mongo_net
    volumes:
      - confservvol3:${CONFIG_SERVER3_CONTAINER_DB_PATH}

networks:
  mongo_net:
    external: true

volumes:
  confservvol1: {}
  confservvol2: {}
  confservvol3: {}
